from enum import Enum


class FinancialIntent(str, Enum):
    DEBT = "DEBT"
    CASHFLOW = "CASHFLOW"
    SAVINGS = "SAVINGS"
    EMERGENCY_FUND = "EMERGENCY_FUND"
    INSURANCE = "INSURANCE"
    INVESTMENT = "INVESTMENT"
    GOAL = "GOAL"
    RETIREMENT = "RETIREMENT"
    TAX = "TAX"
    RISK_PROFILE = "RISK_PROFILE"
    NET_WORTH = "NET_WORTH"
    FINANCIAL_HEALTH = "FINANCIAL_HEALTH"
    SCENARIO = "SCENARIO"
    GENERAL_FINANCIAL_KNOWLEDGE = "GENERAL_FINANCIAL_KNOWLEDGE"